/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace IKana {
  export type BridgeDataStruct = {
    transactionId: PromiseOrValue<BytesLike>;
    bridge: PromiseOrValue<string>;
    integrator: PromiseOrValue<string>;
    referrer: PromiseOrValue<string>;
    sendingAssetId: PromiseOrValue<string>;
    receiver: PromiseOrValue<BytesLike>;
    minAmount: PromiseOrValue<BigNumberish>;
    destinationChainId: PromiseOrValue<BigNumberish>;
    hasSourceSwaps: PromiseOrValue<boolean>;
    hasDestinationCall: PromiseOrValue<boolean>;
  };

  export type BridgeDataStructOutput = [
    string,
    string,
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    boolean,
    boolean
  ] & {
    transactionId: string;
    bridge: string;
    integrator: string;
    referrer: string;
    sendingAssetId: string;
    receiver: string;
    minAmount: BigNumber;
    destinationChainId: BigNumber;
    hasSourceSwaps: boolean;
    hasDestinationCall: boolean;
  };
}

export declare namespace LibSwap {
  export type SwapDataStruct = {
    callTo: PromiseOrValue<string>;
    approveTo: PromiseOrValue<string>;
    sendingAssetId: PromiseOrValue<string>;
    receivingAssetId: PromiseOrValue<string>;
    fromAmount: PromiseOrValue<BigNumberish>;
    callData: PromiseOrValue<BytesLike>;
    requiresDeposit: PromiseOrValue<boolean>;
  };

  export type SwapDataStructOutput = [
    string,
    string,
    string,
    string,
    BigNumber,
    string,
    boolean
  ] & {
    callTo: string;
    approveTo: string;
    sendingAssetId: string;
    receivingAssetId: string;
    fromAmount: BigNumber;
    callData: string;
    requiresDeposit: boolean;
  };
}

export interface GenericSwapFacetInterface extends utils.Interface {
  functions: {
    "getFee()": FunctionFragment;
    "setFee(uint32)": FunctionFragment;
    "swapTokensGeneric(bytes32,string,string,address,uint256,(address,address,address,address,uint256,bytes,bool)[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getFee" | "setFee" | "swapTokensGeneric"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "getFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "swapTokensGeneric",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      LibSwap.SwapDataStruct[]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapTokensGeneric",
    data: BytesLike
  ): Result;

  events: {
    "KanaSwappedGeneric(bytes32,string,string,address,address,uint256,uint256)": EventFragment;
    "KanaTransferCompleted(bytes32,address,address,uint256,uint256)": EventFragment;
    "KanaTransferStarted(tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "KanaSwappedGeneric"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "KanaTransferCompleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "KanaTransferStarted"): EventFragment;
}

export interface KanaSwappedGenericEventObject {
  transactionId: string;
  integrator: string;
  referrer: string;
  fromAssetId: string;
  toAssetId: string;
  fromAmount: BigNumber;
  toAmount: BigNumber;
}
export type KanaSwappedGenericEvent = TypedEvent<
  [string, string, string, string, string, BigNumber, BigNumber],
  KanaSwappedGenericEventObject
>;

export type KanaSwappedGenericEventFilter =
  TypedEventFilter<KanaSwappedGenericEvent>;

export interface KanaTransferCompletedEventObject {
  transactionId: string;
  receivingAssetId: string;
  receiver: string;
  amount: BigNumber;
  timestamp: BigNumber;
}
export type KanaTransferCompletedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  KanaTransferCompletedEventObject
>;

export type KanaTransferCompletedEventFilter =
  TypedEventFilter<KanaTransferCompletedEvent>;

export interface KanaTransferStartedEventObject {
  bridgeData: IKana.BridgeDataStructOutput;
}
export type KanaTransferStartedEvent = TypedEvent<
  [IKana.BridgeDataStructOutput],
  KanaTransferStartedEventObject
>;

export type KanaTransferStartedEventFilter =
  TypedEventFilter<KanaTransferStartedEvent>;

export interface GenericSwapFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GenericSwapFacetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getFee(overrides?: CallOverrides): Promise<[number]>;

    setFee(
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapTokensGeneric(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _referrer: PromiseOrValue<string>,
      _receiver: PromiseOrValue<string>,
      _minAmount: PromiseOrValue<BigNumberish>,
      _swapData: LibSwap.SwapDataStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getFee(overrides?: CallOverrides): Promise<number>;

  setFee(
    _fee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapTokensGeneric(
    _transactionId: PromiseOrValue<BytesLike>,
    _integrator: PromiseOrValue<string>,
    _referrer: PromiseOrValue<string>,
    _receiver: PromiseOrValue<string>,
    _minAmount: PromiseOrValue<BigNumberish>,
    _swapData: LibSwap.SwapDataStruct[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getFee(overrides?: CallOverrides): Promise<number>;

    setFee(
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    swapTokensGeneric(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _referrer: PromiseOrValue<string>,
      _receiver: PromiseOrValue<string>,
      _minAmount: PromiseOrValue<BigNumberish>,
      _swapData: LibSwap.SwapDataStruct[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "KanaSwappedGeneric(bytes32,string,string,address,address,uint256,uint256)"(
      transactionId?: PromiseOrValue<BytesLike> | null,
      integrator?: null,
      referrer?: null,
      fromAssetId?: null,
      toAssetId?: null,
      fromAmount?: null,
      toAmount?: null
    ): KanaSwappedGenericEventFilter;
    KanaSwappedGeneric(
      transactionId?: PromiseOrValue<BytesLike> | null,
      integrator?: null,
      referrer?: null,
      fromAssetId?: null,
      toAssetId?: null,
      fromAmount?: null,
      toAmount?: null
    ): KanaSwappedGenericEventFilter;

    "KanaTransferCompleted(bytes32,address,address,uint256,uint256)"(
      transactionId?: PromiseOrValue<BytesLike> | null,
      receivingAssetId?: null,
      receiver?: null,
      amount?: null,
      timestamp?: null
    ): KanaTransferCompletedEventFilter;
    KanaTransferCompleted(
      transactionId?: PromiseOrValue<BytesLike> | null,
      receivingAssetId?: null,
      receiver?: null,
      amount?: null,
      timestamp?: null
    ): KanaTransferCompletedEventFilter;

    "KanaTransferStarted(tuple)"(
      bridgeData?: null
    ): KanaTransferStartedEventFilter;
    KanaTransferStarted(bridgeData?: null): KanaTransferStartedEventFilter;
  };

  estimateGas: {
    getFee(overrides?: CallOverrides): Promise<BigNumber>;

    setFee(
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapTokensGeneric(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _referrer: PromiseOrValue<string>,
      _receiver: PromiseOrValue<string>,
      _minAmount: PromiseOrValue<BigNumberish>,
      _swapData: LibSwap.SwapDataStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setFee(
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapTokensGeneric(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _referrer: PromiseOrValue<string>,
      _receiver: PromiseOrValue<string>,
      _minAmount: PromiseOrValue<BigNumberish>,
      _swapData: LibSwap.SwapDataStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
