/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace IKana {
  export type BridgeDataStruct = {
    transactionId: PromiseOrValue<BytesLike>;
    bridge: PromiseOrValue<string>;
    integrator: PromiseOrValue<string>;
    referrer: PromiseOrValue<string>;
    sendingAssetId: PromiseOrValue<string>;
    receiver: PromiseOrValue<BytesLike>;
    minAmount: PromiseOrValue<BigNumberish>;
    destinationChainId: PromiseOrValue<BigNumberish>;
    hasSourceSwaps: PromiseOrValue<boolean>;
    hasDestinationCall: PromiseOrValue<boolean>;
  };

  export type BridgeDataStructOutput = [
    string,
    string,
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    boolean,
    boolean
  ] & {
    transactionId: string;
    bridge: string;
    integrator: string;
    referrer: string;
    sendingAssetId: string;
    receiver: string;
    minAmount: BigNumber;
    destinationChainId: BigNumber;
    hasSourceSwaps: boolean;
    hasDestinationCall: boolean;
  };
}

export declare namespace WormholeFacet {
  export type WormholeDataStruct = {
    arbiterFee: PromiseOrValue<BigNumberish>;
    nonce: PromiseOrValue<BigNumberish>;
  };

  export type WormholeDataStructOutput = [BigNumber, number] & {
    arbiterFee: BigNumber;
    nonce: number;
  };
}

export interface WormholeFacetInterface extends utils.Interface {
  functions: {
    "claimToken()": FunctionFragment;
    "startBridgeTokensViaWormhole((bytes32,string,string,address,address,bytes32,uint256,uint256,bool,bool),(uint256,uint32))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "claimToken" | "startBridgeTokensViaWormhole"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startBridgeTokensViaWormhole",
    values: [IKana.BridgeDataStruct, WormholeFacet.WormholeDataStruct]
  ): string;

  decodeFunctionResult(functionFragment: "claimToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startBridgeTokensViaWormhole",
    data: BytesLike
  ): Result;

  events: {
    "KanaTransferCompleted(bytes32,address,address,uint256,uint256)": EventFragment;
    "KanaTransferStarted(tuple)": EventFragment;
    "WormholeChainIdMapped(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "KanaTransferCompleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "KanaTransferStarted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WormholeChainIdMapped"): EventFragment;
}

export interface KanaTransferCompletedEventObject {
  transactionId: string;
  receivingAssetId: string;
  receiver: string;
  amount: BigNumber;
  timestamp: BigNumber;
}
export type KanaTransferCompletedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  KanaTransferCompletedEventObject
>;

export type KanaTransferCompletedEventFilter =
  TypedEventFilter<KanaTransferCompletedEvent>;

export interface KanaTransferStartedEventObject {
  bridgeData: IKana.BridgeDataStructOutput;
}
export type KanaTransferStartedEvent = TypedEvent<
  [IKana.BridgeDataStructOutput],
  KanaTransferStartedEventObject
>;

export type KanaTransferStartedEventFilter =
  TypedEventFilter<KanaTransferStartedEvent>;

export interface WormholeChainIdMappedEventObject {
  lifiChainId: BigNumber;
  wormholeChainId: BigNumber;
}
export type WormholeChainIdMappedEvent = TypedEvent<
  [BigNumber, BigNumber],
  WormholeChainIdMappedEventObject
>;

export type WormholeChainIdMappedEventFilter =
  TypedEventFilter<WormholeChainIdMappedEvent>;

export interface WormholeFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: WormholeFacetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    claimToken(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    startBridgeTokensViaWormhole(
      _bridgeData: IKana.BridgeDataStruct,
      _wormholeData: WormholeFacet.WormholeDataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  claimToken(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  startBridgeTokensViaWormhole(
    _bridgeData: IKana.BridgeDataStruct,
    _wormholeData: WormholeFacet.WormholeDataStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    claimToken(overrides?: CallOverrides): Promise<void>;

    startBridgeTokensViaWormhole(
      _bridgeData: IKana.BridgeDataStruct,
      _wormholeData: WormholeFacet.WormholeDataStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "KanaTransferCompleted(bytes32,address,address,uint256,uint256)"(
      transactionId?: PromiseOrValue<BytesLike> | null,
      receivingAssetId?: null,
      receiver?: null,
      amount?: null,
      timestamp?: null
    ): KanaTransferCompletedEventFilter;
    KanaTransferCompleted(
      transactionId?: PromiseOrValue<BytesLike> | null,
      receivingAssetId?: null,
      receiver?: null,
      amount?: null,
      timestamp?: null
    ): KanaTransferCompletedEventFilter;

    "KanaTransferStarted(tuple)"(
      bridgeData?: null
    ): KanaTransferStartedEventFilter;
    KanaTransferStarted(bridgeData?: null): KanaTransferStartedEventFilter;

    "WormholeChainIdMapped(uint256,uint256)"(
      lifiChainId?: PromiseOrValue<BigNumberish> | null,
      wormholeChainId?: PromiseOrValue<BigNumberish> | null
    ): WormholeChainIdMappedEventFilter;
    WormholeChainIdMapped(
      lifiChainId?: PromiseOrValue<BigNumberish> | null,
      wormholeChainId?: PromiseOrValue<BigNumberish> | null
    ): WormholeChainIdMappedEventFilter;
  };

  estimateGas: {
    claimToken(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    startBridgeTokensViaWormhole(
      _bridgeData: IKana.BridgeDataStruct,
      _wormholeData: WormholeFacet.WormholeDataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    claimToken(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    startBridgeTokensViaWormhole(
      _bridgeData: IKana.BridgeDataStruct,
      _wormholeData: WormholeFacet.WormholeDataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
